" Name:         cortado
" Description:  A warm and energetic colorscheme
" Author:       Jesse Hoyos <jessehoyos@icloud.com>
" Maintainer:   Jesse Hoyos <jessehoyos@icloud.com>
" License:      Vim License (see `:help license`)
" Last Updated: Sat May 16 14:37:42 2020

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'cortado'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#171b23', '#f9815c', '#4fa579', '#c79f5b',
        \ '#4791d1', '#c595b8', '#a1bfe0', '#f6e3c2', '#363d49', '#ffaf8a',
        \ '#1d382c', '#d6bfa9', '#a1bfe0', '#f0da87', '#a1bfe0', '#f0da87']
  if has('nvim')
    let g:terminal_color_0 = '#171b23'
    let g:terminal_color_1 = '#f9815c'
    let g:terminal_color_2 = '#4fa579'
    let g:terminal_color_3 = '#c79f5b'
    let g:terminal_color_4 = '#4791d1'
    let g:terminal_color_5 = '#c595b8'
    let g:terminal_color_6 = '#a1bfe0'
    let g:terminal_color_7 = '#f6e3c2'
    let g:terminal_color_8 = '#363d49'
    let g:terminal_color_9 = '#ffaf8a'
    let g:terminal_color_10 = '#1d382c'
    let g:terminal_color_11 = '#d6bfa9'
    let g:terminal_color_12 = '#a1bfe0'
    let g:terminal_color_13 = '#f0da87'
    let g:terminal_color_14 = '#a1bfe0'
    let g:terminal_color_15 = '#f0da87'
  endif
  if !exists('g:cortado_italic_comments')
    let g:cortado_italic_comments = 1
  endif
  if !exists('g:cortado_italic_functions')
    let g:cortado_italic_functions = 1
  endif
  hi Normal guifg=#d1c3ab guibg=#171b23 guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#171b23 guibg=#f6e3c2 guisp=NONE gui=NONE cterm=NONE
  hi None guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLineNr guifg=#e3ddd8 guibg=#222834 guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#322b2a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#9a7d6a guibg=#222834 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#363d49 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#4fa579 guibg=#222834 guisp=NONE gui=bold cterm=bold
  hi SignColumn guifg=#322b2a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#322b2a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#9a7d6a guibg=#373e48 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#373e48 guibg=#373e48 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#f6e3c2 guibg=#363d49 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#222834 guibg=#222834 guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#f9815c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#453a36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#a1bfe0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#a1bfe0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#c79f5b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#222834 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#222834 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#171b23 guisp=NONE gui=NONE cterm=NONE
  hi QuickFixLine guifg=#171b23 guibg=#4791d1 guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#9a7d6a guibg=#222834 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#363d49 guibg=#171b23 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#322b2a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#171b23 guibg=#d1c3ab guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#171b23 guibg=#d1c3ab guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#171b23 guibg=#4791d1 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#363d49 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#4fa579 guibg=#1d382c guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#373e48 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#f9815c guibg=#4a322e guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#c79f5b guibg=#38342c guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#516585 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#ffaf8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#f9815c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#e3ddd8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#c79f5b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#e3ddd8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#ffaf8a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#9a7d6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#a1bfe0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#a1bfe0 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Include guifg=#c595b8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#c595b8 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Number guifg=#f9815c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#9a7d6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#f6e3c2 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi StorageClass guifg=#c595b8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#f0da87 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#f6e3c2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Todo guifg=#4791d1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#c595b8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#e3ddd8 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi vimOption guifg=#e3ddd8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#f9815c guibg=NONE guisp=#f9815c gui=undercurl cterm=undercurl
  hi SpellCap guifg=#f9815c guibg=NONE guisp=#f9815c gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#f9815c guibg=NONE guisp=#f9815c gui=undercurl cterm=undercurl
  hi SpellRare guifg=#f9815c guibg=NONE guisp=#f9815c gui=undercurl cterm=undercurl
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Function gui=NONE cterm=NONE
    hi Keyword gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
  endif
  let g:indentLine_color_gui  = '#322b2a'
  let g:indentLine_color_term = 236
  let g:limelight_conceal_guifg = '#453a36'
  let g:limelight_conceal_ctermfg = 237
  hi! link Terminal Normal
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link VisualNOS Visual
  hi! link diffAdded DiffAdd
  hi! link diffBDiffer WarningMsg
  hi! link diffChanged DiffChange
  hi! link diffCommon WarningMsg
  hi! link diffDiffer WarningMsg
  hi! link diffFile Directory
  hi! link diffIdentical WarningMsg
  hi! link diffIndexLine Number
  hi! link diffIsA WarningMsg
  hi! link diffNoEOL WarningMsg
  hi! link diffOnly WarningMsg
  hi! link diffRemoved DiffDelete
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Float Constant
  hi! link Conditional Statement
  hi! link Exception Statement
  hi! link Label Statement
  hi! link Repeat Statement
  hi! link Define PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi! link Structure Type
  hi! link Typedef Type
  hi! link Debug Special
  hi! link SpecialChar Special
  hi! link Tag Special
  hi! link Noise Delimiter
  hi! link StringDelimiter Delimiter
  hi! link Conceal Ignore
  hi! link NonText Ignore
  hi! link SpecialKey Ignore
  hi! link EndOfBuffer Ignore
  hi! link Whitespace Ignore
  hi! link Identifier Include
  hi! link Searchlight IncSearch
  hi! link cssBraces Delimiter
  hi! link gitcommitOverflow Error
  hi! link gitcommitSummary Title
  hi! link helpHyperTextJump Underlined
  hi! link htmlArg Function
  hi! link htmlEndTag Delimiter
  hi! link htmlLink Underlined
  hi! link htmlSpecialTagName htmlTagName
  hi! link htmlTag Delimiter
  hi! link htmlTagName Statement
  hi! link rustAttribute Delimiter
  hi! link rustDerive rustAttribute
  hi! link rustDeriveTrait rustDerive
  hi! link rustIdentifier Typedef
  hi! link rustModPath None
  hi! link rustSigil Delimiter
  hi! link scssAttribute Delimiter
  hi! link vimAutoCmdSfxList Type
  hi! link vimAutoEventList Identifier
  hi! link vimCmdSep Special
  hi! link vimCommentTitle SpecialComment
  hi! link vimContinue Delimiter
  hi! link vimHighlight Statement
  hi! link vimUserFunc Function
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownUrl guifg=#453a36 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownCode guifg=NONE guibg=#373e48 guisp=NONE gui=NONE cterm=NONE
  hi markdownFaded guifg=#453a36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link markdownBlockquote None
  hi! link markdownCodeBlock markdownCode
  hi! link markdownCodeDelimiter markdownCode
  hi! link markdownH1Delimiter markdownH1
  hi! link markdownH2Delimiter markdownH2
  hi! link markdownH3Delimiter markdownH3
  hi! link markdownH4Delimiter markdownH4
  hi! link markdownH5Delimiter markdownH5
  hi! link markdownH6Delimiter markdownH6
  hi! link markdownId markdownFaded
  hi! link markdownIdDeclaration markdownFaded
  hi! link markdownLinkDelimiter markdownFaded
  hi! link markdownLinkText None
  hi! link markdownLinkTextDelimiter markdownFaded
  hi! link markdownListMarker markdownFaded
  hi! link markdownRule None
  if !s:italics
    hi markdownItalic gui=NONE cterm=NONE
  endif
  if !g:cortado_italic_comments
    hi Comment        cterm=NONE gui=NONE
    hi SpecialComment cterm=NONE gui=NONE
  endif
  if !g:cortado_italic_functions
    hi Function       cterm=NONE gui=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if !exists('g:cortado_italic_comments')
    let g:cortado_italic_comments = 1
  endif
  if !exists('g:cortado_italic_functions')
    let g:cortado_italic_functions = 1
  endif
  hi Normal ctermfg=187 ctermbg=234 cterm=NONE
  if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
    set background=dark
  endif
  hi Cursor ctermfg=234 ctermbg=223 cterm=NONE
  hi None ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=253 ctermbg=235 cterm=NONE
  hi FoldColumn ctermfg=236 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=137 ctermbg=235 cterm=NONE
  hi LineNr ctermfg=237 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=72 ctermbg=235 cterm=bold
  hi SignColumn ctermfg=236 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=236 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=137 ctermbg=237 cterm=NONE
  hi PmenuSbar ctermfg=237 ctermbg=237 cterm=NONE
  hi PmenuSel ctermfg=223 ctermbg=237 cterm=NONE
  hi PmenuThumb ctermfg=235 ctermbg=235 cterm=NONE
  hi ErrorMsg ctermfg=209 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=237 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=110 ctermbg=NONE cterm=NONE
  hi Question ctermfg=110 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=179 ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi QuickFixLine ctermfg=234 ctermbg=32 cterm=NONE
  hi StatusLine ctermfg=137 ctermbg=235 cterm=NONE
  hi StatusLineNC ctermfg=237 ctermbg=234 cterm=NONE
  hi VertSplit ctermfg=236 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=234 ctermbg=187 cterm=NONE
  hi IncSearch ctermfg=234 ctermbg=187 cterm=NONE
  hi Search ctermfg=234 ctermbg=32 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffAdd ctermfg=72 ctermbg=236 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffDelete ctermfg=209 ctermbg=237 cterm=NONE
  hi DiffText ctermfg=179 ctermbg=236 cterm=NONE
  hi Comment ctermfg=60 ctermbg=NONE cterm=italic
  hi Constant ctermfg=216 ctermbg=NONE cterm=NONE
  hi Error ctermfg=209 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=253 ctermbg=NONE cterm=NONE
  hi Special ctermfg=179 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=253 ctermbg=NONE cterm=NONE
  hi Type ctermfg=216 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=137 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=110 ctermbg=NONE cterm=NONE
  hi Function ctermfg=110 ctermbg=NONE cterm=italic
  hi Include ctermfg=139 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=139 ctermbg=NONE cterm=italic
  hi Number ctermfg=209 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=137 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=223 ctermbg=NONE cterm=italic
  hi StorageClass ctermfg=139 ctermbg=NONE cterm=NONE
  hi String ctermfg=222 ctermbg=NONE cterm=NONE
  hi Title ctermfg=223 ctermbg=NONE cterm=bold
  hi Todo ctermfg=32 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=139 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=253 ctermbg=NONE cterm=underline
  hi vimOption ctermfg=253 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=209 ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=209 ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=209 ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=209 ctermbg=NONE cterm=undercurl
  if !s:italics
    hi Comment cterm=NONE
    hi Function cterm=NONE
    hi Keyword cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  let g:indentLine_color_gui  = '#322b2a'
  let g:indentLine_color_term = 236
  let g:limelight_conceal_guifg = '#453a36'
  let g:limelight_conceal_ctermfg = 237
  hi! link Terminal Normal
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link VisualNOS Visual
  hi! link diffAdded DiffAdd
  hi! link diffBDiffer WarningMsg
  hi! link diffChanged DiffChange
  hi! link diffCommon WarningMsg
  hi! link diffDiffer WarningMsg
  hi! link diffFile Directory
  hi! link diffIdentical WarningMsg
  hi! link diffIndexLine Number
  hi! link diffIsA WarningMsg
  hi! link diffNoEOL WarningMsg
  hi! link diffOnly WarningMsg
  hi! link diffRemoved DiffDelete
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Float Constant
  hi! link Conditional Statement
  hi! link Exception Statement
  hi! link Label Statement
  hi! link Repeat Statement
  hi! link Define PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi! link Structure Type
  hi! link Typedef Type
  hi! link Debug Special
  hi! link SpecialChar Special
  hi! link Tag Special
  hi! link Noise Delimiter
  hi! link StringDelimiter Delimiter
  hi! link Conceal Ignore
  hi! link NonText Ignore
  hi! link SpecialKey Ignore
  hi! link EndOfBuffer Ignore
  hi! link Whitespace Ignore
  hi! link Identifier Include
  hi! link Searchlight IncSearch
  hi! link cssBraces Delimiter
  hi! link gitcommitOverflow Error
  hi! link gitcommitSummary Title
  hi! link helpHyperTextJump Underlined
  hi! link htmlArg Function
  hi! link htmlEndTag Delimiter
  hi! link htmlLink Underlined
  hi! link htmlSpecialTagName htmlTagName
  hi! link htmlTag Delimiter
  hi! link htmlTagName Statement
  hi! link rustAttribute Delimiter
  hi! link rustDerive rustAttribute
  hi! link rustDeriveTrait rustDerive
  hi! link rustIdentifier Typedef
  hi! link rustModPath None
  hi! link rustSigil Delimiter
  hi! link scssAttribute Delimiter
  hi! link vimAutoCmdSfxList Type
  hi! link vimAutoEventList Identifier
  hi! link vimCmdSep Special
  hi! link vimCommentTitle SpecialComment
  hi! link vimContinue Delimiter
  hi! link vimHighlight Statement
  hi! link vimUserFunc Function
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownUrl ctermfg=237 ctermbg=NONE cterm=underline
  hi markdownCode ctermfg=NONE ctermbg=237 cterm=NONE
  hi markdownFaded ctermfg=237 ctermbg=NONE cterm=NONE
  hi! link markdownBlockquote None
  hi! link markdownCodeBlock markdownCode
  hi! link markdownCodeDelimiter markdownCode
  hi! link markdownH1Delimiter markdownH1
  hi! link markdownH2Delimiter markdownH2
  hi! link markdownH3Delimiter markdownH3
  hi! link markdownH4Delimiter markdownH4
  hi! link markdownH5Delimiter markdownH5
  hi! link markdownH6Delimiter markdownH6
  hi! link markdownId markdownFaded
  hi! link markdownIdDeclaration markdownFaded
  hi! link markdownLinkDelimiter markdownFaded
  hi! link markdownLinkText None
  hi! link markdownLinkTextDelimiter markdownFaded
  hi! link markdownListMarker markdownFaded
  hi! link markdownRule None
  if !s:italics
    hi markdownItalic cterm=NONE
  endif
  if !g:cortado_italic_comments
    hi Comment        cterm=NONE gui=NONE
    hi SpecialComment cterm=NONE gui=NONE
  endif
  if !g:cortado_italic_functions
    hi Function       cterm=NONE gui=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: base0        #171b23 ~ # Background
" Color: base1        #222834 ~ # Slightly lighter
" Color: base2        #373e48 ~ # Much lighter
" Color: base3        #363d49 ~ # Lightest
" Color: base4        #322b2a ~ # Almost invisible
" Color: base5        #453a36 ~ # Much darker
" Color: base6        #9a7d6a ~ # Slightly darker
" Color: base7        #d1c3ab ~ # Foreground
" Color: base8        #f6e3c2 ~ # Lighter
" Color: royal        #4791d1 ~
" Color: sea          #a1bfe0 ~
" Color: grass        #4fa579 ~
" Color: lemon        #f0da87 ~
" Color: lily         #c595b8 ~
" Color: sorbet       #ffaf8a ~
" Color: heat         #f9815c ~
" Color: blonde       #c79f5b ~
" Color: mill         #d6bfa9 ~
" Color: milk         #e3ddd8 ~
" Color: green_wash   #1d382c ~
" Color: red_wash     #4a322e ~
" Color: yellow_wash  #38342c ~
" Color: cyan_wash    #516585 ~
" Term Colors:  base0  heat    grass       blonde
" Term Colors:  royal  lily    sea         base8
" Term Colors:  base3  sorbet  green_wash  mill
" Term Colors:  sea    lemon   sea         lemon
" vim: et ts=2 sw=2
